"""Build the 30-DJ seed list for the April 13 DM round.

Picks 30 working Madrid-based DJs from the existing dj_profiles.json,
prioritising the ones with confirmed genres (the curated tier 1 picks).
Outputs YAML at data/madrid_dj_seed_list.yaml.

Each entry: name, sc_handle, sc_url, genres, dm_template_variant.
Marvin reviews + edits before April 13.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
PROFILES = ROOT / "src" / "data" / "dj_profiles.json"
OUT = ROOT / "data" / "madrid_dj_seed_list.yaml"

# Tier 1: top Madrid scene names with confirmed genres
TIER_1_PRIORITY = [
    "Oscar Mulero",
    "Cristian Varela",
    "Indira Paganotto",
    "Henry Saiz",
    "Hector Couto",
    "Dennis Cruz",
    "Pional",
    "Chus",
    "404Error",
    "Wally Lopez",
    "Guti",
    "Sparrow & Barbossa",
    "Chris Figueroa",
    "Pomboklap",
    "Dj Pepo",
    "Unkle Fon",
    "Shelley Johannsen",
    "DJ Fra",
    "Hector",  # Vami
    "Nano",
]


def main() -> None:
    data = json.load(open(PROFILES))
    items = data if isinstance(data, list) else list(data.values())
    madrid = [
        d for d in items
        if isinstance(d, dict) and d.get("city") == "Madrid" and d.get("soundcloud")
    ]

    # Build a name → record map
    by_name = {d["name"]: d for d in madrid}

    seed: list[dict] = []

    # First pass: tier 1 in priority order
    for name in TIER_1_PRIORITY:
        if name in by_name:
            d = by_name[name]
            seed.append(_make_entry(d, tier=1))

    # Second pass: fill to 30 with the next best picks (the ones with genres set)
    for d in madrid:
        if len(seed) >= 30:
            break
        if d["name"] in TIER_1_PRIORITY:
            continue
        if not d.get("genres"):
            continue
        seed.append(_make_entry(d, tier=2))

    # Third pass: fill remaining slots with whatever's left
    for d in madrid:
        if len(seed) >= 30:
            break
        if d["name"] in {e["name"] for e in seed}:
            continue
        seed.append(_make_entry(d, tier=3))

    # Write YAML manually (no PyYAML dep)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# Madrid DJ seed list — 30 personalized DM targets for April 13\n")
        f.write("# Generated by scripts/build_dj_seed_list.py\n")
        f.write("# Marvin: review, edit, kill any that don't fit, add Instagram handles where missing.\n")
        f.write("\n")
        f.write("djs:\n")
        for entry in seed:
            f.write(f"  - name: \"{entry['name']}\"\n")
            f.write(f"    sc_handle: \"{entry['sc_handle']}\"\n")
            f.write(f"    sc_url: \"{entry['sc_url']}\"\n")
            f.write(f"    instagram: \"\"  # FILL IN MANUALLY\n")
            f.write(f"    tier: {entry['tier']}\n")
            f.write(f"    genres: {entry['genres']}\n")
            f.write(f"    dm_variant: \"{entry['dm_variant']}\"\n")
            f.write(f"    note: \"{entry['note']}\"\n")
            f.write("\n")

    print(f"✓ wrote {len(seed)} DJs to {OUT.relative_to(ROOT)}")
    print()
    print("Tier breakdown:")
    for t in [1, 2, 3]:
        n = sum(1 for e in seed if e["tier"] == t)
        if n:
            print(f"  Tier {t}: {n}")


def _make_entry(profile: dict, tier: int) -> dict:
    handle = profile["soundcloud"]
    genres = profile.get("genres", [])

    # Pick DM template variant based on what we know about the DJ
    if tier == 1:
        variant = "A"  # personal — for DJs Marvin probably knows
    elif genres:
        variant = "B"  # discovered via SC
    else:
        variant = "C"  # found via venue/promoter

    note = ""
    if "techno" in genres and "minimal" not in genres:
        note = "Techno scene — likely Bunker Bear or Hard Rhino target"
    elif "house" in genres:
        note = "House scene — Disco Flamingo or Lounge Lynx target"
    elif genres:
        note = f"{', '.join(genres[:2])} — character TBD by scan"
    else:
        note = "Genres unknown — character will be assigned by scan"

    return {
        "name": profile["name"],
        "sc_handle": handle,
        "sc_url": f"https://soundcloud.com/{handle}",
        "tier": tier,
        "genres": genres,
        "dm_variant": variant,
        "note": note,
    }


if __name__ == "__main__":
    main()
